In [4]:
from random import choice
import numpy as np
import matplotlib.pyplot as plt
from copy import copy
import time
from IPython import display
import re

In [1]:
conda install scikit-learn

Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - scikit-learn


The following packages will be UPDATED:

  ca-certificates    conda-forge::ca-certificates-2020.12.~ --> pkgs/main::ca-certificates-2021.1.19-hecd8cb5_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            conda-forge::certifi-2020.12.5-py37hf~ --> pkgs/main::certifi-2020.12.5-py37hecd8cb5_0
  conda              conda-forge::conda-4.9.2-py37hf985489~ --> pkgs/main::conda-4.9.2-py37hecd8cb5_0
  openssl            conda-forge::openssl-1.1.1i-h35c211d_0 --> pkgs/main::openssl-1.1.1i-h9ed2024_0


Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.


In [1]:
import nltk
import sklearn

print('The nltk version is {}.'.format(nltk.__version__))
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The nltk version is 3.5.
The scikit-learn version is 0.23.2.


In [2]:
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))

matplotlib: 3.3.2


In [3]:
pip list

Package                       Version            
----------------------------- -------------------
absl-py                       0.11.0             
anaconda-client               1.7.2              
anaconda-navigator            1.9.7              
appnope                       0.1.0              
asn1crypto                    1.3.0              
astor                         0.8.1              
astunparse                    1.6.3              
attrs                         19.3.0             
backcall                      0.1.0              
backports.functools-lru-cache 1.6.1              
backports.tempfile            1.0                
backports.weakref             1.0.post1          
beautifulsoup4                4.8.2              
bleach                        3.1.0              
cachetools                    4.1.1              
certifi                       2020.12.5          
cffi                          1.14.0             
chardet                       3.0.4              


In [3]:
conda install pandas

Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-1.2.1               |   py37hb2f4e1b_0         8.1 MB
    ------------------------------------------------------------
                                           Total:         8.1 MB

The following NEW packages will be INSTALLED:

  pandas             pkgs/main/osx-64::pandas-1.2.1-py37hb2f4e1b_0



pandas-1.2.1         | 8.1 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.


In [4]:
conda install -c conda-forge matplotlib

Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.12.5          |   py37hf985489_1         143 KB  conda-forge
    openssl-1.1.1i             |       h35c211d_0         1.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.0 MB

The following packages will be UPDATED:

  certifi            pkgs/main::certifi-2020.12.5-py37hecd~ --> conda-forge::certifi-2020.12.5-py37hf985489_1

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2021.1.19-~ --> conda-forge::ca-certificates-2020.12.5-h033912b_0
  conda               pkgs/main::conda-4.9.2-py37hecd8cb5_0 --> conda-forge::conda-4.9.2-py37hf9854

In [2]:
board_str = 'xxxx__oooo'
board = np.array(list(board_str))

print("board: "+board_str)
i = np.random.randint(4)
j = np.random.randint(5, 6)
print('x goes from {:d} -> {:d}'.format(i, j))
print(i,j)
board[i] = '_'
board[j] = 'x'

#print(board)
board_str = ''.join(board)
print("board: "+board_str)

sel_o = np.where(board == 'o')[0]
#print(sel_o)
emp = np.where(board == '_')[0]
print((sel_o))
i = np.random.choice((sel_o))
j = np.random.choice(emp)

print(i,j)
board[i] = '_'
board[j] = 'o'

#print(board)
print('o goes from {:d} -> {:d}'.format(i, j))
board_str = ''.join(board)
print("board: "+board_str)

match_xox = re.search("xox", board_str)
match_oxo = re.search("oxo", board_str)
flag = False
if match_xox != None:
    flag = True
    matchpos = re.search("xox", board_str).start()
    print(matchpos)
    o_pos = matchpos +2 // 2
    print(o_pos)
    board[o_pos] ='_'
    board_str = ''.join(board)
    print("o at position {:d}; killed".format(o_pos))
    print(board_str)
    
if flag == False and match_oxo != None:
    matchpos = re.search("oxo", board_str).start()
    print(matchpos)
    x_pos = matchpos +2 // 2
    print(x_pos)
    board[x_pos] ='_'
    board_str = ''.join(board)
    print("x at position {:d}; killed".format(x_pos))
    print(board_str)




board: xxxx__oooo
x goes from 1 -> 5
1 5
board: x_xx_xoooo
[6 7 8 9]
7 4
o goes from 7 -> 4
board: x_xxoxo_oo
3
4
o at position 4; killed
x_xx_xo_oo


In [3]:
def getij(option):
    sel = np.where(board == option)[0]
    emp = np.where(board == '_')[0]
    i_pos = np.random.choice(sel)
    j_pos = np.random.choice(emp)
    return i_pos, j_pos

In [4]:
def checkVals(brd):
    selx = np.where(brd == 'x')[0]
    selo = np.where(brd == 'o')[0]

    return len(selo) == 1 or len(selx) == 1

In [5]:
'''
Testing
'''
board_str1 = '___x__oooo'
board1 = np.array(list(board_str1))

if checkVals(board1):
    print("T")
else :
    print("f")

T


In [8]:
"""
Indicies
"""
def play():
    board_str = 'xxxx__oooo'
    board = np.array(list(board_str))
    
    x = np.array([])

    for k in range(100):
        print("board: " + board_str)

        if k == 0:
            i = np.random.randint(4)
            j = np.random.randint(5, 6)
        else:
            i, j = getij('x')

        print('x goes from {:d} -> {:d}'.format(i, j))
        board[i] = '_'
        board[j] = 'x'
        board_str = ''.join(board)
        print("board: " + board_str)
        board_x = -1*(board_str == 'x') + 1*(board_str == 'o') + 0*(board_str == '_')

        if k != 0:
            match_oxo = re.search("oxo", board_str)
            if match_oxo is not None:
                matchpos = re.search("oxo", board_str).start()
                x_pos = matchpos + 2 // 2
                board[x_pos] = '_'
                board_str = ''.join(board)
                print("x at position {:d}; killed".format(x_pos))

            match_xox = re.search("xox", board_str)
            if match_xox is not None:
                matchpos = re.search("xox", board_str).start()
                o_pos = matchpos + 2 // 2
                board[o_pos] = '_'
                board_str = ''.join(board)
                print("o at position {:d}; killed".format(o_pos))

        i, j = getij('o')
        # sel_o = np.where(board == 'o')[0]
        # emp = np.where(board == '_')[0]
        # i = np.random.choice((sel_o))
        # j = np.random.choice(emp)

        board[i] = '_'
        board[j] = 'o'

        print('o goes from {:d} -> {:d}'.format(i, j))
        board_str = ''.join(board)
        print("board: " + board_str)
        board_o = -1*(self.board_arr == 'x') + 1*(self.board_arr == 'o') + 0*(self.board_arr == '_')

        match_xox = re.search("xox", board_str)
        match_oxo = re.search("oxo", board_str)
        #match = re.search("xo+x",board)


        flag = False

        if match_xox is not None:
            flag = True
            matchpos = re.search("xox", board_str).start()
            o_pos = matchpos + 2 // 2
            board[o_pos] = '_'
            board_str = ''.join(board)
            print("o at position {:d}; killed".format(o_pos))

        if flag == False and match_oxo is not None:
            matchpos = re.search("oxo", board_str).start()
            x_pos = matchpos + 2 // 2
            board[x_pos] = '_'
            board_str = ''.join(board)
            print("x at position {:d}; killed".format(x_pos))
        
        data = np.concatenate((board_x , board_o ))
        
        if step == 0:
                x= data
            else:
                x = np.vstack((x, data))

        if checkVals(board):
            break
    print("Done")

In [10]:
play()

board: xxxx__oooo
x goes from 0 -> 5
board: _xxx_xoooo
o goes from 8 -> 2
board: _xox_xoo_o
o at position 2; killed
board: _x_x_xoo_o
x goes from 9 -> 1
board: _x_x_xoo__
o goes from 6 -> 3
board: _x_o_x_o__
board: _x_o_x_o__
x goes from 9 -> 0
board: xx_o_x_o__
o goes from 4 -> 0
board: ox_o_x_o__
board: ox_o_x_o__
x goes from 9 -> 3
board: ox_x_x_o__
o goes from 8 -> 5
board: ox_x_o_o__
board: ox_x_o_o__
x goes from 9 -> 3
board: ox_x_o_o__
o goes from 8 -> 0
board: ox_x_o_o__
board: ox_x_o_o__
x goes from 9 -> 5
board: ox_x_x_o__
o goes from 6 -> 2
board: oxox_x_o__
o at position 2; killed
board: ox_x_x_o__
x goes from 9 -> 5
board: ox_x_x_o__
o goes from 8 -> 1
board: oo_x_x_o__
board: oo_x_x_o__
x goes from 9 -> 5
board: oo_x_x_o__
o goes from 4 -> 5
board: oo_x_o_o__
Done


In [50]:
board = 'xoooxxoox__oo'
#board = 'xxxx_ooo'
match1 = re.findall("xo+x",board)
print(match1)

i =1 
for pattern in match1 :
    match2 = re.search(pattern, board)
    #print(match2)
    print("iteration :"+ str(i))
    print(match2.span())
    idx = match2.span()
    #print(type(idx))
    print(idx[0] , idx[1])
    i = i+1
    # code to replace o's between x
    p_len = idx[1] - idx[0]
    board[:idx[0]+1]+"_"+board[p_len-1:]
    print(board)

['xooox', 'xoox']
iteration :1
(0, 5)
0 5
xoooxxoox__oo
iteration :2
(5, 9)
5 9
xoooxxoox__oo


In [ ]:
if 0-5

x=0 and the othe 5-1

x1 = 0 and x2 = 5-1

# from x1+1 to x2-1


In [31]:
board = 'xoooxoox__oo'
#board = 'xxxx_ooo'
match1 = re.findall("xo+x",board)
print(match1)

['xooox']


In [42]:
def findpattern(board):
    match1 = re.findall("xo+x",board)
    return match1

In [41]:
board = 'x___xoox__oo'
ret = findpattern(board)
if len(ret)>0:
    # replace o's between x

1


In [62]:
array1 = [1,2,3,4,5]
array2 = [1,2,3,4,6]

total = []
total.append(array1)
#print(total)
total.append(array2)
#print(total)

arr = np.array(total)

# print(array1.shape())

print(arr)
# for item in total:
#     print(item)

[[1 2 3 4 5]
 [1 2 3 4 6]]


In [8]:
board_str = 'xxxx__oooo' 
board1 = np.array([board_str])
board_x = -1 * (board1 == 'x') + 1 * (board1 == 'o') + 0 * (board1 == '_')
print(board_x)

[0]


In [10]:
def getboard(board_str):
    data= []
    for i in range(0,len(board_str)):
        if board_str[i] == 'x':
            data.append(-1)
        elif board_str[i] == 'o':
            data.append(1)
        else:
            data.append(0)
    return data

In [11]:
board_str = 'xxxx__oooo' 
board_x = getboard(board_str)
print(board_x)

[-1, -1, -1, -1, 0, 0, 1, 1, 1, 1]
